language: python
python:
  - 2.7
  - 3.6
dist: trusty
cache: pip

addons:
  apt:
    packages:
      - vera++
      - cutter-testing-framework-bin

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  # Bring pip up to date 
  - pip install --upgrade pip setuptools wheel
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git

install:
  - pip install -r requirements-test.txt
  - pip install python-coveralls 'coverage>=4.4'
  - python ./setup.py install
  # C build checks
  - make -C c_data_specification -f test.mk build-test
  # TODO: ensure that the C data spec also builds with the embedded compiler

script:
  # Tests
  - py.test unittests --cov data_specification
  - py.test integration_tests --cov data_specification --cov-append
  - make -C c_data_specification -f test.mk check
  # Code quality check
  - flake8 data_specification
  - flake8 unittests integration_tests
  - support/run-vera.sh c_data_specification
  # Build check
  - cd doc/source
  - sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls
