# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

language: python
dist: focal
python:
  - 2.7
  - 3.6
  - 3.7
addons:
  apt:
    packages:
      - openjdk-8-jre-headless
      - ant
cache: pip

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  - support/rat.sh download
  # Bring pip up to date
  - pip install --upgrade pip setuptools wheel
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git

install:
  - pip install -r requirements-test.txt
  - pip install 'pylint<2.5' python-coveralls 'coverage>=4.4,<5.0'
  - python ./setup.py install

script:
  # Tests
  - py.test unittests --cov data_specification
  # Code quality check
  - flake8 data_specification
  - ( pylint --output-format=colorized --disable=R,C data_specification; exit $(($? & 35)) )
  - support/rat.sh run
  # Build check
  - support/travis-sphinx.sh html -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - support/travis-sphinx.sh json -q -T -b json -d _build/doctrees-json -D language=en . _build/json
  - support/travis-sphinx.sh singlehtml -q -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls
