language: python
dist: xenial
python:
  - 2.7
  - 3.6
matrix:
  include:
    - python: 3.7
      sudo: true
cache: pip

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  # Bring pip up to date 
  - pip install --upgrade pip setuptools wheel
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git

install:
  - pip install -r requirements-test.txt
  - pip install python-coveralls 'coverage>=4.4'
  - python ./setup.py install

script:
  # Tests
  - py.test unittests --cov data_specification
  - py.test integration_tests --cov data_specification --cov-append
  # Code quality check
  - flake8 data_specification
  - flake8 unittests integration_tests
  # Build check
  - support/travis-sphinx.sh html -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - support/travis-sphinx.sh json -T -b json -d _build/doctrees-json -D language=en . _build/json
  - support/travis-sphinx.sh singlehtml -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls
