# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Publish

on:
  #workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOY_DIR: doc/source/_build/html
      DEPS: SpiNNUtils SpiNNMachine
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout SupportScripts
        uses: actions/checkout@v2
        with:
          repository: SpiNNakerManchester/SupportScripts
          path: support
      - name: Checkout SpiNNaker Dependencies
        run: |
          for dep in $DEPS; do
            support/gitclone2.sh https://github.com/SpiNNakerManchester/$dep.git
          done
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          for dep in $DEPS; do
            (cd $dep || exit 1; exec python setup.py install)
          done
          pip install -r requirements-test.txt

      - name: Build Python Documentation
        run: support/travis-sphinx.sh html -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html

      - name: Prepare for deployment
        run: |
          touch .nojekyll
        working-directory: ${{ env.DEPLOY_DIR }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ${{ env.DEPLOY_DIR }}
